# coding: utf-8
# generated by: sqlacodegen mysql+pymysql://root:root@localhost/ebreakfast_db --outfile models.py
#
from sqlalchemy import Column, Date, Float, ForeignKey, String, Table, text
from sqlalchemy.dialects.mysql import INTEGER
from sqlalchemy.orm import relationship
# from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import declarative_base

Base = declarative_base()
metadata = Base.metadata


class Address(Base):
    __tablename__ = 'addresses'

    id = Column(INTEGER(11), primary_key=True)
    street = Column(String(80), nullable=False)
    city = Column(String(20), nullable=False)
    zip = Column(String(20), nullable=False)
    country = Column(String(80), server_default=text("'United States'"))


class Creditcard(Base):
    __tablename__ = 'creditcards'

    id = Column(String(80), primary_key=True)
    numbers = Column(String(80), nullable=False)
    zip = Column(String(20), nullable=False)

    customers = relationship('Customer', secondary='paymentmethods')


class Merchant(Base):
    __tablename__ = 'merchants'

    id = Column(String(20), primary_key=True)
    email = Column(String(20))
    phone = Column(String(20))
    tax_id = Column(String(20))


class Customer(Base):
    __tablename__ = 'customers'

    id = Column(String(20), primary_key=True)
    email = Column(String(20))
    phone = Column(String(20))
    birthdate = Column(Date)
    address_fk = Column(ForeignKey('addresses.id', ondelete='CASCADE'), nullable=False, index=True)

    address = relationship('Address')


class Restaurant(Base):
    __tablename__ = 'restaurants'

    id = Column(String(20), primary_key=True)
    email = Column(String(20))
    phone = Column(String(20))
    merchant_fk = Column(ForeignKey('merchants.id', ondelete='CASCADE'), nullable=False, index=True)

    merchant = relationship('Merchant')


class Meal(Base):
    __tablename__ = 'meals'

    id = Column(String(20), primary_key=True)
    descr = Column(String(80))
    price = Column(Float(5, True))
    restaurant_fk = Column(ForeignKey('restaurants.id', ondelete='CASCADE'), nullable=False, index=True)

    restaurant = relationship('Restaurant')
    orders = relationship('Order', secondary='ordermeals')


class Order(Base):
    __tablename__ = 'orders'

    id = Column(INTEGER(11), primary_key=True)
    customer_fk = Column(ForeignKey('customers.id', ondelete='CASCADE'), nullable=False, index=True)

    customer = relationship('Customer')


t_paymentmethods = Table(
    'paymentmethods', metadata,
    Column('customer_fk', ForeignKey('customers.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('creditcard_fk', ForeignKey('creditcards.id', ondelete='CASCADE'), nullable=False, index=True)
)


t_ordermeals = Table(
    'ordermeals', metadata,
    Column('order_fk', ForeignKey('orders.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('meal_fk', ForeignKey('meals.id', ondelete='CASCADE'), nullable=False, index=True)
)



if __name__ == '__main__':
    from sqlalchemy import create_engine
    from sqlalchemy.orm import Session

    # engine = create_engine("mysql+pymysql://root:root@localhost/ebreakfast_db", echo=True, future=True)
    engine = create_engine("mysql+pymysql://root:root@localhost/ebreakfast_db", future=True)
    with Session(engine) as session:
        add1 = Address(street='street1011', city='city101', zip='55555')
        cc1 = Creditcard(id='cc11112', numbers='444444444444444', zip='44444')
        session.add(add1)
        session.commit()  
        session.add(cc1)
        print(f'---> {add1.id}')
        cust1 = Customer(id='cust11111', email='cust1@example.com', phone='3333333333', birthdate='2000-7-07', address_fk=add1.id)
        session.add(cust1)
        session.commit()

